In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install -q transformers scikit-learn tqdm pandas torch

In [ ]:
!pip install -U transformers accelerate

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.1)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.11.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.8.0+cu126)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.10.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)

In [ ]:
import os
os.environ["WANDB_DISABLED"] = "true"

DATASET_PATH = "s7_dataset_fixed.csv"
MODEL_NAME = "distilbert/distilbert-base-multilingual-cased"
MAX_LEN = 256
BATCH_SIZE = 16
EPOCHS = 3
SEED = 42

In [ ]:
import csv

input_file = './s7_dataset.csv'
output_file = './s7_dataset_fixed.csv'

def fix_csv_file(input_file, output_file):
  rows_fixed = []

  with open(input_file, 'r', encoding='utf-8-sig', newline='') as infile:
    lines = infile.readlines()

    header = ['message_id', 'text', 'level1_category', 'level2_labels']
    rows_fixed.append(header)

    for i, line in enumerate(lines[1:], start=1):
      line = line.strip()
      if not line:
        continue

      if line.startswith('"') and line.endswith('"'):
        line = line[1:-1]
        line = line.replace('""', '"')

      first_comma = line.find(',')
      if first_comma == -1:
        print(f"Предупреждение: строка {i} пропущена (нет запятой)")
        continue

      message_id = line[:first_comma].strip()
      rest = line[first_comma+1:]

      parts = rest.rsplit(',', 2)

      if len(parts) == 3:
        text = parts[0].strip()
        level1 = parts[1].strip()
        level2 = parts[2].strip()
        rows_fixed.append([message_id, text, level1, level2])
      else:
        print(f"Предупреждение: строка {i} не разобрана корректно")
        continue

    with open(output_file, 'w', encoding='utf-8', newline='') as outfile:
        writer = csv.writer(
          outfile,
          delimiter=',',
          quotechar='"',
          quoting=csv.QUOTE_MINIMAL
          )

        for row in rows_fixed:
          writer.writerow(row)

    print(f"✓ Файл успешно исправлен!")
    print(f"✓ Исходный файл: {input_file}")
    print(f"✓ Исправленный файл: {output_file}")
    print(f"✓ Обработано строк: {len(rows_fixed)} (включая заголовок)")

    return len(rows_fixed)

fix_csv_file(input_file, output_file)

✓ Файл успешно исправлен!
✓ Исходный файл: ./s7_dataset.csv
✓ Исправленный файл: ./s7_dataset_fixed.csv
✓ Обработано строк: 11906 (включая заголовок)

11906

In [ ]:
import numpy as np
from sklearn.metrics import classification_report
import torch
def evaluate_model(model, tokenizer, X_val, Y_val, mlb):

    print("\n--- Оценка модели ---")
    with torch.no_grad():
        all_preds = []
        for i in range(len(X_val)):
            enc = tokenizer(
                X_val[i],
                truncation=True,
                padding='max_length',
                max_length=MAX_LEN,
                return_tensors='pt'
            )
            for k in enc:
                enc[k] = enc[k].to(model.device)
            logits = model(**enc).logits
            sigmoid = torch.sigmoid(logits).cpu().numpy()[0]
            pred_bin = (sigmoid > 0.5).astype(int)
            all_preds.append(pred_bin)
        all_preds = np.vstack(all_preds)

    print(classification_report(Y_val, all_preds, target_names=mlb.classes_, zero_division=0))

In [ ]:
import pandas as pd
from collections import Counter
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
import torch
from sklearn.metrics import f1_score, classification_report
import joblib

df = pd.read_csv(DATASET_PATH)
df = df[~df['level2_labels'].isna()]

cat_cleanup = {
    "Лояцность и продажи": "Лояльность и продажи",
    "До Вылетa": "До Вылета"
}

df['level1_category'] = df['level1_category'].replace(cat_cleanup)


for l1 in sorted(df['level1_category'].unique()):
    df_sub = df[df['level1_category'] == l1].copy()

    def clean_label(label):
        return label.replace('«', '').replace('»', '').replace('"', '').replace("'", '').replace("”", '').replace("“", '').strip()
    def clean_list(labels):
        return [clean_label(l) for l in labels if clean_label(l)]

    df_sub['level2_list'] = df_sub['level2_labels'].astype(str).str.split(";").apply(clean_list)

    all_labels = [l for labels in df_sub['level2_list'] for l in labels]
    label_counts = Counter(all_labels)
    allowed_labels = set([l for l, cnt in label_counts.items() if cnt >= 2])
    df_sub['level2_list'] = df_sub['level2_list'].apply(lambda labels: [l for l in labels if l in allowed_labels])
    df_sub = df_sub[df_sub['level2_list'].map(len) > 0]
    if len(df_sub) < 30 or len(allowed_labels) < 2:
        print(f"Пропускаю категорию L1 {l1}, слишком мало данных для обучения")
        continue
    print(f"--- Обучаем модель для L1={l1} (строк: {len(df_sub)}, меток: {len(allowed_labels)}) ---")


    mlb = MultiLabelBinarizer()
    Y = mlb.fit_transform(df_sub['level2_list'])
    X_train, X_val, Y_train, Y_val = train_test_split(
        df_sub['text'].tolist(), Y, test_size=0.15, random_state=SEED
    )

    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    class L2Dataset(torch.utils.data.Dataset):
        def __init__(self, texts, ys):
            self.texts = texts
            self.labels = ys
        def __len__(self): return len(self.texts)
        def __getitem__(self, i):
            enc = tokenizer(
                self.texts[i],
                padding='max_length',
                truncation=True,
                max_length=MAX_LEN,
                return_tensors='pt'
            )
            item = {k: v.squeeze(0) for k, v in enc.items()}
            item['labels'] = torch.tensor(self.labels[i], dtype=torch.float)
            return item

    train_ds = L2Dataset(X_train, Y_train)
    val_ds = L2Dataset(X_val, Y_val)

    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=Y.shape[1],
        problem_type="multi_label_classification"
    )
    training_args = TrainingArguments(
        output_dir=f"./l2_models/{l1.replace(' ', '_')}",
        num_train_epochs=EPOCHS,
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE * 2,
        save_strategy="epoch",
        save_total_limit=2,
        seed=SEED,
        fp16=True if torch.cuda.is_available() else False,
        logging_steps=100,
    )
    def compute_metrics(p):
        preds = (torch.sigmoid(torch.tensor(p.predictions)) > 0.5).int().cpu().numpy()
        f1_micro = f1_score(p.label_ids, preds, average='micro', zero_division=0)
        f1_macro = f1_score(p.label_ids, preds, average='macro', zero_division=0)
        return {
            'f1_micro': f1_micro,
            'f1_macro': f1_macro
        }

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        compute_metrics=compute_metrics,
        tokenizer=tokenizer
    )

    trainer.train()
    trainer.save_model(f"./l2_models/{l1.replace(' ', '_')}")
    tokenizer.save_pretrained(f"./l2_models/{l1.replace(' ', '_')}")
    joblib.dump(mlb, f"./l2_models/{l1.replace(' ', '_')}/level2_mlb.joblib")

    evaluate_model(model, tokenizer, X_val, Y_val, mlb)

--- Обучаем модель для L1=Вылет Прилет (строк: 1450, меток: 5) ---

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/466 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/542M [00:00<?, ?B/s]

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert/distilbert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
/tmp/ipython-input-717101332.py:94: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

--- Оценка модели ---
                    precision    recall  f1-score   support

Гостиница трансфер       1.00      1.00      1.00        40
    Задержка рейса       0.99      0.98      0.99       125
      Отмена рейса       0.99      0.99      0.99        88
      Поиск багажа       0.99      0.99      0.99       167
      Статус рейса       0.96      0.92      0.94        86

         micro avg       0.99      0.98      0.98       506
         macro avg       0.99      0.98      0.98       506
      weighted avg       0.99      0.98      0.98       506
       samples avg       0.98      0.98      0.98       506

--- Обучаем модель для L1=До Вылета (строк: 1455, меток: 5) ---

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert/distilbert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
/tmp/ipython-input-717101332.py:94: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

--- Оценка модели ---
                   precision    recall  f1-score   support

Багаж (до вылета)       0.98      0.94      0.96        53
     Бронирование       0.95      0.85      0.90        73
        Документы       0.98      0.92      0.95        49
           Оплата       0.98      0.96      0.97        67
      Регистрация       0.98      0.87      0.92        47

        micro avg       0.97      0.91      0.94       289
        macro avg       0.97      0.91      0.94       289
     weighted avg       0.97      0.91      0.94       289
      samples avg       0.98      0.93      0.95       289

Пропускаю категорию L1 Другое, слишком мало данных для обучения
--- Обучаем модель для L1=Лояльность и продажи (строк: 1500, меток: 2) ---

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert/distilbert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
/tmp/ipython-input-717101332.py:94: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

--- Оценка модели ---
                      precision    recall  f1-score   support

        Акции тарифы       0.99      0.99      0.99       105
Программа лояльности       0.99      0.99      0.99       120

           micro avg       0.99      0.99      0.99       225
           macro avg       0.99      0.99      0.99       225
        weighted avg       0.99      0.99      0.99       225
         samples avg       0.99      0.99      0.99       225

--- Обучаем модель для L1=На борту (строк: 1450, меток: 6) ---

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert/distilbert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
/tmp/ipython-input-717101332.py:94: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

--- Оценка модели ---
                   precision    recall  f1-score   support

       Багаж борт       1.00      0.87      0.93        52
     Комфорт борт       0.98      0.98      0.98       129
Обслуживание борт       0.99      0.97      0.98       128
     Питание борт       0.96      0.98      0.97        95
 Развлечения борт       0.99      0.99      0.99        90
     Чистота борт       0.92      0.92      0.92        78

        micro avg       0.98      0.96      0.97       572
        macro avg       0.97      0.95      0.96       572
     weighted avg       0.98      0.96      0.97       572
      samples avg       0.95      0.94      0.94       572

--- Обучаем модель для L1=Обратная связь (строк: 1400, меток: 4) ---

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert/distilbert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
/tmp/ipython-input-717101332.py:94: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

--- Оценка модели ---
               precision    recall  f1-score   support

Благодарность       1.00      1.00      1.00        52
       Жалоба       1.00      1.00      1.00        54
  Предложение       1.00      1.00      1.00        52
    Эскалация       1.00      1.00      1.00        52

    micro avg       1.00      1.00      1.00       210
    macro avg       1.00      1.00      1.00       210
 weighted avg       1.00      1.00      1.00       210
  samples avg       1.00      1.00      1.00       210

--- Обучаем модель для L1=После вылета (строк: 1500, меток: 4) ---

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert/distilbert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
/tmp/ipython-input-717101332.py:94: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

--- Оценка модели ---
                          precision    recall  f1-score   support

          Возврат билета       1.00      1.00      1.00        84
             Компенсация       1.00      1.00      1.00        57
            Обмен билета       1.00      1.00      1.00        69
Потерянная собственность       1.00      1.00      1.00        70

               micro avg       1.00      1.00      1.00       280
               macro avg       1.00      1.00      1.00       280
            weighted avg       1.00      1.00      1.00       280
             samples avg       1.00      1.00      1.00       280

--- Обучаем модель для L1=Сервисные (строк: 450, меток: 2) ---

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert/distilbert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
/tmp/ipython-input-717101332.py:94: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

--- Оценка модели ---
              precision    recall  f1-score   support

 Приветствие       0.91      0.94      0.93        34
    Прощание       0.94      0.91      0.93        34

   micro avg       0.93      0.93      0.93        68
   macro avg       0.93      0.93      0.93        68
weighted avg       0.93      0.93      0.93        68
 samples avg       0.93      0.93      0.93        68

--- Обучаем модель для L1=Технические вопросы (строк: 1500, меток: 2) ---

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert/distilbert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
/tmp/ipython-input-717101332.py:94: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

--- Оценка модели ---
                         precision    recall  f1-score   support

            Работа бота       1.00      1.00      1.00       108
Работа сайта приложения       1.00      1.00      1.00       117

              micro avg       1.00      1.00      1.00       225
              macro avg       1.00      1.00      1.00       225
           weighted avg       1.00      1.00      1.00       225
            samples avg       1.00      1.00      1.00       225